# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='movies',
            field=models.ManyToManyField(to='movielist.Movie'),
        ),
    ]
